name: Test Ruby

on: [push, pull_request]

jobs:
  test-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Install RSpec
        run: gem install rspec
      - name: Run Ruby tests
        run: |
          ruby/test
