name: Test Haskell

on: [push, pull_request]

jobs:
  test-haskell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.4.8"
          cabal-version: "3.10.1.0"
      - name: Install Test.Hspec globally
        run: cabal update && cabal install --lib hspec
      - name: Run Haskell tests
        run: haskell/test
